import React, { useState } from 'react';
import { 
  Play, 
  Layers, 
  CheckCircle2, 
  Copy, 
  Check, 
  Database, 
  Terminal, 
  Send,
  Sparkles
} from 'lucide-react';
import { useWorkspace } from '../../context/WorkspaceContext';
import { EndpointSpec } from '../../types/project';

export const ApiTester: React.FC = () => {
  const { apiContract, databaseSchema, addTerminalLog } = useWorkspace();
  const endpoints = apiContract?.endpoints || [];

  const [selectedEndpoint, setSelectedEndpoint] = useState<EndpointSpec>(endpoints[0] || {
    id: 'ep_def',
    method: 'GET',
    path: '/api/v1/health',
    description: 'System health check',
    responseSchema: '{ status: "ok" }',
    status: 'tested',
    sampleResponse: { status: 'healthy', uptime: 34200, dbLatency: '2.1ms', database: 'connected' }
  });

  const [requestBody, setRequestBody] = useState('{\n  "title": "Quantum Compute Cluster",\n  "description": "High performance agent node",\n  "price": 399.00\n}');
  const [responseOutput, setResponseOutput] = useState<any>(selectedEndpoint.sampleResponse || { status: 'healthy' });
  const [statusCode, setStatusCode] = useState<number>(200);
  const [latencyMs, setLatencyMs] = useState<number>(2.4);
  const [copied, setCopied] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const handleSendRequest = () => {
    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      const isPost = selectedEndpoint.method === 'POST';
      setStatusCode(isPost ? 201 : 200);
      setLatencyMs(Math.round((Math.random() * 4 + 1.2) * 10) / 10);

      if (isPost) {
        try {
          const parsed = JSON.parse(requestBody);
          setResponseOutput({
            success: true,
            item: {
              id: 'itm_' + Math.random().toString(36).substr(2, 6),
              ...parsed,
              createdAt: new Date().toISOString()
            },
            message: `Record saved to ${databaseSchema.type.toUpperCase()} database`
          });
        } catch {
          setResponseOutput({ success: true, message: 'Created record' });
        }
      } else {
        setResponseOutput(selectedEndpoint.sampleResponse || { status: 'healthy' });
      }

      addTerminalLog(`[API TESTER] ${selectedEndpoint.method} ${selectedEndpoint.path} -> ${isPost ? '201 Created' : '200 OK'} (${latencyMs}ms)`, 'success');
    }, 250);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(JSON.stringify(responseOutput, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full flex flex-col bg-[#090b11] p-4 overflow-y-auto space-y-4">
      {/* Top Banner */}
      <div className="p-4 rounded-xl bg-[#0f121e] border border-[#1f253d] flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-blue-500/20">
            <Layers className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white font-sans">
              In-IDE API Request Runner
            </h2>
            <p className="text-xs text-slate-400">
              Live testing console for backend endpoints generated by Backend Agent.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
          <span className="text-slate-500">Base URL:</span>
          <span className="text-cyan-400 font-semibold">{apiContract?.baseUrl || 'http://localhost:5000'}</span>
        </div>
      </div>

      {/* Main Split: Endpoints List on Left / Runner on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 flex-1">
        {/* Endpoints Sidebar */}
        <div className="rounded-xl bg-[#0f121e] border border-[#1f253d] p-3 space-y-2">
          <div className="text-[11px] font-mono font-bold text-slate-300 uppercase tracking-wider mb-2">
            Discovered Endpoints ({endpoints.length})
          </div>

          <div className="space-y-1.5">
            {endpoints.map((ep) => (
              <button
                key={ep.id}
                onClick={() => {
                  setSelectedEndpoint(ep);
                  setResponseOutput(ep.sampleResponse || { status: 'healthy' });
                }}
                className={`w-full text-left p-2.5 rounded-lg transition border flex flex-col gap-1 ${
                  selectedEndpoint.id === ep.id
                    ? 'bg-cyan-950/60 border-cyan-800 text-cyan-300'
                    : 'bg-[#141828] border-[#222942] text-slate-300 hover:bg-[#191f33]'
                }`}
              >
                <div className="flex items-center gap-2">
                  <span className={`text-[10px] font-mono font-bold px-1.5 py-0.5 rounded ${
                    ep.method === 'GET' ? 'bg-blue-950 text-blue-400' : 'bg-emerald-950 text-emerald-400'
                  }`}>
                    {ep.method}
                  </span>
                  <span className="font-mono text-xs font-semibold truncate">{ep.path}</span>
                </div>
                <span className="text-[10px] text-slate-400 truncate">{ep.description}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Request & Response Console */}
        <div className="lg:col-span-2 space-y-4">
          {/* Request Header Bar */}
          <div className="rounded-xl bg-[#0f121e] border border-[#1f253d] p-4 space-y-3">
            <div className="flex items-center gap-2">
              <span className={`text-xs font-mono font-bold px-2 py-1 rounded ${
                selectedEndpoint.method === 'GET' ? 'bg-blue-950 text-blue-400' : 'bg-emerald-950 text-emerald-400'
              }`}>
                {selectedEndpoint.method}
              </span>
              <input
                type="text"
                readOnly
                value={`${apiContract?.baseUrl || 'http://localhost:5000'}${selectedEndpoint.path}`}
                className="flex-1 px-3 py-1.5 text-xs font-mono rounded-lg bg-[#090b11] border border-[#20273e] text-white"
              />
              <button
                onClick={handleSendRequest}
                disabled={isLoading}
                className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold transition shadow-md shadow-blue-600/20 active:scale-95 disabled:opacity-50"
              >
                <Send className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
                <span>Send</span>
              </button>
            </div>

            {selectedEndpoint.method === 'POST' && (
              <div>
                <label className="text-[11px] font-mono text-slate-400 mb-1 block">Request Body (JSON)</label>
                <textarea
                  value={requestBody}
                  onChange={(e) => setRequestBody(e.target.value)}
                  rows={4}
                  className="w-full p-2.5 text-xs font-mono rounded-lg bg-[#090b11] border border-[#20273e] text-cyan-300 focus:outline-none focus:border-cyan-500"
                />
              </div>
            )}
          </div>

          {/* Response Box */}
          <div className="rounded-xl bg-[#0f121e] border border-[#1f253d] p-4 space-y-3">
            <div className="flex items-center justify-between text-xs font-mono">
              <div className="flex items-center gap-2">
                <span className="text-slate-400">Response Status:</span>
                <span className="px-2 py-0.5 rounded bg-emerald-950 text-emerald-400 font-bold border border-emerald-800">
                  {statusCode} {statusCode === 201 ? 'Created' : 'OK'}
                </span>
                <span className="text-slate-500">• {latencyMs} ms</span>
              </div>

              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-slate-400 hover:text-cyan-400 transition"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy JSON'}</span>
              </button>
            </div>

            <pre className="p-3.5 rounded-lg bg-[#07090f] border border-[#20273c] text-emerald-400 font-mono text-xs overflow-auto max-h-72 leading-relaxed">
              {JSON.stringify(responseOutput, null, 2)}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};
